[package]
name = "navar-tokio"
version = "0.1.0"
edition = "2024"

[dependencies]
navar = { path = ".." }
tokio = { version = "1", features = ["net"] }
tokio-util = { version = "0.7", features = ["compat"] }
anyhow = "1.0"
