[package]
name = "navar-iroh"
version = "0.1.0"
edition = "2024"

[dependencies]
navar = { path = ".." }
iroh = "0.95.1"
tokio = { version = "1", features = ["sync"] }
anyhow = "1.0"
tokio-util = { version = "0.7", features = ["compat"] }
dashmap = "6.1.0"
futures = "0.3.31"
